### ISSUE TITLE
How to set the module icon

### ISSUE THREAD

**Issue by l4ci** [lukaskleinschmidt/kirby-sortable#1]
In your preview - you have different icons for text and gallery - how did you achieve that?

**Comment by lukaskleinschmidt** [comment]
Sry for the long delay.
You can just set the Icon in the modules blueprint:

`gallery.yml`

```
title: Gallery module
pages: false
icon: picture-o
files:
  type: image
  sortable: true
  fields:
    alt:
      label: Alternative text
      type: text
fields:
  title:
    label: Module title
type: text
```

https://getkirby.com/docs/panel/blueprints/form-fields#custom-icons
