### ISSUE TITLE
Undefined property field::options

### ISSUE THREAD

**Issue by Thiousi** [lukaskleinschmidt/kirby-sortable#11]
I've just installed the latest version of the plugin and the field and get an error in the panel:

```
Notice: Undefined property: Kirby\Panel\Models\Page\Blueprint\Field::$options in D:\Git\Natasa\site\fields\modules\controller.php on line 9
Warning: array_filter() expects parameter 1 to be array, null given in D:\Git\Natasa\site\fields\modules\controller.php on line 69
```

As far as I can tell, everything is working fine except for that part :(

Here's my blueprint. I have tried with just label and type and with every combination of options I could think of:

```
  modules:
    label: Sections
    type: modules
    style: items
    readonly: false
    options:
      redirect: false
      preview: true
      delete: true
      limit: null
      edit: true
```

**Comment by lukaskleinschmidt** [comment]
I will take a look at this

**Comment by Thiousi** [comment]
In a weird twist, rebooting my computer and relaunching everything fixed this ... 
Sorry I can't provide more information to help with this !

**Comment by lukaskleinschmidt** [comment]
Odd one.
I'll try to poke around to see if I can reproduce this somehow.
Do you register the modules with the new regestry?

**Comment by Thiousi** [comment]
Nope, I've just upgraded from an old version of both your field and the plugin to the latest version of both but haven't tried out the registry yet.

**Comment by Andi-Lo** [comment]
I got the same error:

![bug](https://cloud.githubusercontent.com/assets/7545568/18531323/1810f8b4-7ad6-11e6-9da3-2ec3894ebb69.PNG)

``` yml
  modules:
    label: Modules
    type: modules
```

I can remove the error when I add the options field into the blueprint. 

``` yml
  modules:
    label: Modules
    type: modules
    options:
      limit: null
```

This does work.
