### ISSUE TITLE
How to override the language variables ?

### ISSUE THREAD

**Issue by Thiousi** [lukaskleinschmidt/kirby-sortable#12]
I tried copying the language variables to my config file to override them (my client doesn't understand modules but sections are fine) but to no effect. Is there any way to override the language variables without touching at the plugin files ?

**Comment by lukaskleinschmidt** [comment]
Thats a tricky one.
As far as I know there is no build in feature.

I did some testing. Somehow it's not possible to access langugage strings in a field set in the config.php. Althoug I disabled the language loader in the field.

Perhaps something like this could be suitable.

``` yml
label: Sections
type: modules
translate:
  en:
    fields.modules.visible: Visible sections
    fields.modules.visible.info: Drag invisible sections here to sort them/make them visible.
```

But for now a fork would be the easiest way I think.
