### ISSUE TITLE
Long module titles break the layout

### ISSUE THREAD

**Issue by medienbaecker** [lukaskleinschmidt/kirby-sortable#37]
The `.sortable-layout__title` element has `white-space` set to `nowrap` and breaks the layout of the panel when there's too much text inside:

![bildschirmfoto 2017-08-30 um 12 57 04](https://user-images.githubusercontent.com/7975568/29869304-c39930e2-8d82-11e7-8b95-bb61676d94a0.png)

This is especially noticable on the mobile version, where even short titles are enough to push everything off to the right:

![bildschirmfoto 2017-08-30 um 13 00 31](https://user-images.githubusercontent.com/7975568/29869456-43881be2-8d83-11e7-9646-299be17aa6e6.png)

**Comment by lukaskleinschmidt** [comment]
Thats because of a bug with fieldsets.
https://github.com/getkirby/panel/pull/986

You could add the styles from the PR in a custom panel css. I will add an info to the readme with a fix for that.

```css
.form-blueprint-checklist > fieldset {
  min-width: 0;
}

@-moz-document url-prefix() {
  .form-blueprint-checklist > fieldset {
    display: table-cell;
  }
}

```

See https://github.com/lukaskleinschmidt/kirby-sortable#5-known-bugs
