### ISSUE TITLE
Hide page in module section

### ISSUE THREAD

**Issue by findthebug** [lukaskleinschmidt/kirby-sortable#48]
I have updated the modules and sortable plugin to the latest version. So far all is working but one thing i can't get done. In the Panel on the right side where the modules are diplayed, also the normal page are shown. how can i disable the normal pages in the sortable section? in the old version of modules and sortable plugin, normal pages are hidden in the module section on the right side. do i miss something? 

![bildschirmfoto 2018-04-17 um 13 34 33](https://user-images.githubusercontent.com/5121132/38867632-d97b3e60-4244-11e8-949a-b6556c16a5ea.png)

**Comment by lukaskleinschmidt** [comment]
How does your blueprint file look like?
Are you using the `modules` or the `sortable` field type?

**Comment by findthebug** [comment]
At the moment im testing it on the projects template with the sortable field type. I did the basic kirby installation and added just the sortable default definition to the blueprint. 

Toolkit Version: 2.5.10
Kirby Version: 2.5.10
Panel Version: 2.5.10

projects.yml
```
title: Projects
files: true
options:
  preview: true
  status: true
  template: true
  url: true
  delete: true  
pages:
  hide: false
  template:
    - module.text
    - module.gallery 
fields:
  title:
    label: Title
    type:  text
  sortable:
    label: Sortable
    type:  sortable
    sortable: true
    layout:  base
    variant: null
    limit: false
    parent: null
    prefix: null
    options:
      limit: false
```

Here is the basic installation to reproduce the behaviour. login/pw root/root
[kirby.zip](https://github.com/lukaskleinschmidt/kirby-sortable/files/1919938/kirby.zip)

**Comment by lukaskleinschmidt** [comment]
Please try to use the `modules` field type. Both fields ship with this plugin.
The `modules` field itself is an extended `sortable` field and [overrides](https://github.com/lukaskleinschmidt/kirby-sortable/blob/master/fields/modules/modules.php) the [`prefix`](https://github.com/lukaskleinschmidt/kirby-sortable#prefix) and [`parent`](https://github.com/lukaskleinschmidt/kirby-sortable#parent) options. This way the plugin knows which pages it should handle.

Your blueprint should look like this.
```yml
title: Projects
files: true
options:
  preview: true
  status: true
  template: true
  url: true
  delete: true  
pages:
  hide: false
  template:
    - module.text
    - module.gallery 
fields:
  title:
    label: Title
    type: text
  modules:
    label: Modules
    type: modules
```

Basically you could also use the `sortable` field if you set the [`prefix`](https://github.com/lukaskleinschmidt/kirby-sortable#prefix) and [`parent`](https://github.com/lukaskleinschmidt/kirby-sortable#parent) option accordingly.
